language: ruby
sudo: false

rvm: 2.2

cache: bundler

services:
  - memcached
  - redis

addons:
  postgresql: 9.3

before_script:
  - psql postgres -q < spec/support/db.sql

script:
  - bundle exec rspec --require spec_helper
